// <auto-generated> by gen_fishdata.py from the game's WTFish data - do not edit.
namespace WT2Gatherer
{
    static class FishData
    {
        // Per fish: id, names (id, item id, localized item names), and 4 bytes per step:
        // FishBite, useToCatch, useToStayHooked, hookedAfterBite.
        public static readonly FishDef[] All =
        {
            new FishDef("Alburnus", new[] { "Alburno", "Alburnus", "Lambari", "Верховодка", "Уклейка", "ブリーク", "欧白鱼", "백조어" }, new byte[] { 4, 2, 4, 1, 1, 0, 4, 0, 4, 2, 2, 0 }),
            new FishDef("Anarhichas", new[] { "Anarhichas", "Kurtbalığı", "Peixe-Lobo", "Pez lobo", "Poisson-loup", "Wolffish", "Зубатка", "オオカミウオ", "狼鱼", "늑대고기" }, new byte[] { 0, 3, 4, 1, 3, 3, 1, 0, 2, 3, 2, 0, 3, 3, 1, 0, 1, 3, 3, 0, 1, 3, 2, 0, 2, 1, 1, 0 }),
            new FishDef("Anglerfish", new[] { "Anglerfish", "Baudroie", "Peixe-Lanterna", "Rape", "Риба-вудильник", "Рыба-удильщик", "アンコウ", "琵琶鱼", "아귀" }, new byte[] { 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0 }),
            new FishDef("BasicGarbage", new[] { "BasicGarbage" }, new byte[] { 3, 3, 4, 1, 3, 3, 4, 0, 3, 0, 4, 0, 1, 0, 4, 0 }),
            new FishDef("BigClam", new[] { "BigClam" }, new byte[] { 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0, 0, 3, 4, 0 }),
            new FishDef("Capelin", new[] { "Capelan", "Capelin", "Capelán", "Lodde", "Sardinha", "Мойва", "シシャモ", "毛鳞鱼", "열빙어" }, new byte[] { 0, 3, 4, 0, 2, 0, 4, 1, 2, 0, 0, 0 }),
            new FishDef("Carp", new[] { "Carp", "Carpa", "Carpe", "Karp", "Karpfen", "Karpis", "Sazan", "Карп", "Короп", "コイ", "鲤鱼", "잉어" }, new byte[] { 0, 3, 4, 0, 0, 3, 4, 0, 2, 3, 4, 1, 3, 3, 2, 0, 2, 0, 0, 0 }),
            new FishDef("Catfish", new[] { "Bagre", "Catfish", "Kedi Balığı", "Pesce gatto", "Poisson-chat", "Siluro", "Sum", "Wels", "Šamas", "Сом", "ナマズ", "鲶鱼", "메기" }, new byte[] { 2, 3, 4, 1, 3, 3, 3, 0, 4, 3, 1, 0, 4, 3, 1, 0, 1, 3, 3, 0, 1, 1, 1, 0 }),
            new FishDef("Cod", new[] { "Bacalao", "Bacalhau", "Cod", "Morue", "Треска", "Тріска", "タラ", "鳕鱼", "대구" }, new byte[] { 3, 3, 4, 0, 2, 3, 1, 1, 3, 3, 3, 0, 4, 0, 3, 0, 4, 0, 0, 0 }),
            new FishDef("Crucian", new[] { "Carassin", "Crucian", "Cruciano", "Havuz Balığı", "Karausche", "Karaś", "Karosas", "Piaba", "Карась", "フナ", "鲫鱼", "붕어" }, new byte[] { 1, 3, 4, 0, 0, 3, 4, 1, 2, 0, 4, 0, 0, 0, 0, 0 }),
            new FishDef("Flounder", new[] { "Flet", "Flounder", "Pacu", "Pisi Balığı", "Platija", "Камбала", "ヒラメ", "比目鱼", "가자미" }, new byte[] { 3, 3, 3, 1, 4, 3, 1, 0, 4, 3, 2, 0, 1, 3, 3, 0, 4, 3, 2, 0, 4, 2, 2, 0 }),
            new FishDef("Garbage20", new[] { "Garbage20" }, new byte[] { 3, 3, 4, 1, 3, 3, 4, 0, 3, 0, 4, 0, 1, 0, 4, 0 }),
            new FishDef("GarbageStartingIsland", new[] { "GarbageStartingIsland" }, new byte[] { 3, 3, 4, 1, 3, 3, 4, 0, 3, 0, 4, 0, 1, 0, 0, 0 }),
            new FishDef("GarbageTier1", new[] { "GarbageTier1" }, new byte[] { 3, 3, 4, 1, 3, 3, 4, 0, 3, 0, 4, 0, 1, 0, 0, 0 }),
            new FishDef("Halibut", new[] { "Flétan blanc", "Halibut", "Halibut blanco", "Linguado Branco", "White halibut", "Белый палтус", "Білий палтус", "オヒョウ", "白大比目鱼", "흰 넙치" }, new byte[] { 0, 3, 4, 1, 1, 3, 3, 0, 2, 3, 1, 0, 3, 3, 1, 0, 3, 3, 3, 0, 1, 0, 0, 0 }),
            new FishDef("HalibutSmall", new[] { "Black halibut", "Flétan noir", "Halibut negro", "HalibutSmall", "Linguado Negro", "Чорний палтус", "Чёрный палтус", "カレイ", "黑大比目鱼", "검은 넙치" }, new byte[] { 0, 3, 4, 1, 1, 3, 3, 0, 2, 3, 1, 0, 3, 3, 1, 0, 2, 0, 4, 0, 2, 0, 0, 0 }),
            new FishDef("Ide", new[] { "Dourado", "Ide", "Idea", "Язь", "オルフェ", "石斑鱼", "황어" }, new byte[] { 0, 3, 4, 0, 0, 3, 4, 0, 4, 2, 4, 1, 2, 0, 4, 0, 4, 2, 4, 0, 2, 0, 0, 0 }),
            new FishDef("Jellyfish", new[] { "Jellyfish", "Medusa", "Méduse", "Água-Viva", "Медуза", "クラゲ", "水母", "해파리" }, new byte[] { 2, 0, 4, 1, 2, 0, 4, 0, 2, 0, 0, 0 }),
            new FishDef("Mussel", new[] { "Mejillón", "Mexilhão", "Midye", "Moule", "Mussel", "Мидия", "Мідія", "ムール貝", "贻贝", "홍합" }, new byte[] { 1, 3, 4, 1, 2, 4, 4, 0, 1, 1, 0, 0 }),
            new FishDef("Pike", new[] { "Brochet", "Hecht", "Luccio", "Lucio", "Lydeka", "Lúcio", "Pike", "Szczupak", "Turna Balığı", "Щука", "パイク", "梭鱼", "강꼬치고기" }, new byte[] { 4, 3, 4, 1, 2, 3, 3, 0, 4, 3, 2, 0, 4, 3, 1, 0, 1, 0, 0, 0 }),
            new FishDef("Piranha", new[] { "Pirana", "Piranha", "Pirania", "Piraña", "Пиранья", "Піранья", "ピラニア", "水虎鱼", "피라냐" }, new byte[] { 1, 3, 4, 0, 1, 3, 2, 0, 4, 3, 1, 1, 3, 2, 2, 0, 4, 0, 0, 0 }),
            new FishDef("Pufferfish", new[] { "Baiacu", "Balon balığı", "Pez globo", "Poisson-globe", "Pufferfish", "Rozdymka", "Морской ёж", "Морський їжак", "フグ", "河豚", "복어" }, new byte[] { 3, 3, 3, 0, 3, 3, 1, 1, 2, 3, 3, 0, 3, 3, 2, 0, 3, 3, 3, 0, 2, 1, 1, 0 }),
            new FishDef("Roach", new[] { "Gardon", "Hamamböceği", "Pardelha", "Pez cucaracha", "Plötze", "Płoć", "Raudė", "Roach", "Плотва", "ウグイ", "小鱼", "로치" }, new byte[] { 0, 3, 4, 0, 0, 3, 4, 0, 1, 3, 4, 1, 0, 0, 0, 0 }),
            new FishDef("Salmon", new[] { "Lachs", "Salmon", "Salmão", "Salmón", "Saumon", "Лосось", "シャケ", "鲑鱼", "연어" }, new byte[] { 0, 3, 3, 0, 4, 3, 2, 1, 3, 3, 3, 0, 1, 3, 1, 0, 2, 3, 3, 0, 4, 2, 2, 0 }),
            new FishDef("SeaBass", new[] { "Bar commun", "Lubina", "Robalo", "SeaBass", "Морской окунь", "Морський окунь", "スズキ", "鲈鱼", "농어" }, new byte[] { 3, 3, 4, 0, 1, 3, 1, 1, 4, 3, 2, 0, 2, 1, 4, 0, 2, 1, 1, 0 }),
            new FishDef("Shrimp", new[] { "Camarão", "Camarón", "Crevette", "Shrimp", "Креветка", "エビ", "虾", "새우" }, new byte[] { 2, 0, 4, 1, 0, 0, 4, 0, 0, 0, 0, 0 }),
            new FishDef("Sprat", new[] { "Arenque", "Espadín", "Sprat", "Килька", "Кілька", "キビナゴ", "鲷鱼", "청어" }, new byte[] { 0, 0, 4, 1, 0, 0, 4, 0, 0, 0, 0, 0 }),
            new FishDef("Trout", new[] { "Alabalık", "Forelle", "Pstrąg", "Trota", "Trout", "Trucha", "Truite", "Truta", "Upėtakis", "Форель", "マス", "鳟鱼", "송어" }, new byte[] { 0, 3, 4, 0, 3, 3, 4, 0, 2, 3, 4, 1, 1, 3, 2, 0, 4, 3, 1, 0, 1, 0, 0, 0 }),
        };
    }
}
