"""Generate FishData.cs (fish bite sequences + localized names) for the fishing helper.

Run after a game update, with the extractor's venv:
    bin/.venv/bin/python mod/gatherer/gen_fishdata.py
Sequences come from the WTFish ScriptableObjects (same pipeline as bin/extract.py, using its parse
cache); names come from the wiki's public/data/i18n/*.json so the fish list the server sends in any
language can be matched.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "bin"))

from extract import DEFAULT_GAME  # noqa: E402
from wt2.model import Builder  # noqa: E402
from wt2.unity import Game  # noqa: E402


def main():
    builder = Builder(Game(Path(DEFAULT_GAME), ROOT / "bin" / ".cache"))
    locales = {p.stem: json.loads(p.read_text(encoding="utf-8")) for p in sorted((ROOT / "public/data/i18n").glob("*.json"))}

    rows = []
    for fish_id, d in sorted(builder.by_cls["WTFish"].items()):
        items = [builder.ref(x) for x in d.get("itemTypes", []) if builder.ref(x)]
        names = {fish_id}
        if len(items) == 1:  # garbage "fish" have many items; only real fish are listed by name
            names.add(items[0])
            names.update(loc[f"Item.{items[0]}"] for loc in locales.values() if f"Item.{items[0]}" in loc)
        steps = []
        for a in d.get("actions", []):
            steps += [a["fishBite"], a["useToCatch"], a["useToStayHooked"], 1 if a.get("hookedAfterBite") else 0]
        rows.append((fish_id, sorted(names), steps))

    out = [
        "// <auto-generated> by gen_fishdata.py from the game's WTFish data - do not edit.",
        "namespace WT2Gatherer",
        "{",
        "    static class FishData",
        "    {",
        "        // Per fish: id, names (id, item id, localized item names), and 4 bytes per step:",
        "        // FishBite, useToCatch, useToStayHooked, hookedAfterBite.",
        "        public static readonly FishDef[] All =",
        "        {",
    ]
    for fish_id, names, steps in rows:
        name_list = ", ".join(json.dumps(n, ensure_ascii=False) for n in names)
        out.append(f'            new FishDef("{fish_id}", new[] {{ {name_list} }}, new byte[] {{ {", ".join(map(str, steps))} }}),')
    out += ["        };", "    }", "}", ""]
    target = Path(__file__).with_name("FishData.cs")
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {len(rows)} fish to {target}")


if __name__ == "__main__":
    main()
